version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gru
      POSTGRES_PASSWORD: gru
      POSTGRES_DB: gru
